import NavBar from '../components/NavBar';
import '../style/mainPage.css'

export default function mainPage() {
    return (
        <>
        <NavBar/>
        <div className='divPortfolio'>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>

            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>
            <p>Olá, React!</p>

        </div>
        </>
    )
}